package com.jf.bchyj.action.system.bbgl;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import net.sf.json.JSONObject;
import com.jf.util.DrawTable;
import mt.controller.InitAction;
import mt.controller.base.ServletObject;

public class ScHtmlAction extends InitAction {

	protected void actionQuery(ServletObject so) {
		String jfid=so.httpServletRequest.getParameter("code");
		try {
			StringBuffer htmlAll=new StringBuffer("");
			//----------------------------------------------------------------
			htmlAll.append("<%@ page language='java' import='java.util.*' pageEncoding='GBK'%>");
			htmlAll.append("<%@ taglib uri='/WEB-INF/mt.tld' prefix='mt'%>");
			htmlAll.append("<%@page import='com.jf.util.DrawTable'%>");
			htmlAll.append("<%@page import='com.jf.bchyj.bean.User'%>");
			htmlAll.append("<%@page import='java.util.Date'%>");
			htmlAll.append("<%@page import='java.text.DateFormat'%>");
			htmlAll.append("<%@page import='java.text.SimpleDateFormat'%>");
			htmlAll.append("<html>");
			htmlAll.append("<head><title>数据填报</title>");
			htmlAll.append("<script type='text/javascript' src='/insect/javascript/jquery-1.8.3.min.js'></script>");
			htmlAll.append("<script type='text/javascript' src='/insect/javascript/function.js'></script>");
			htmlAll.append("<script type='text/javascript' src='/insect/javascript/jy.js'></script>");
			htmlAll.append("<script type='text/javascript' src='/insect/javascript/My97DatePicker/WdatePicker.js'></script>");
			htmlAll.append("<script type='text/javascript' src='/insect/javascript/common.js'></script>");
			htmlAll.append("<script type='text/javascript'>");
			htmlAll.append("var ops=new Array();");
			htmlAll.append("var f=1;");
			htmlAll.append("function xuanze(obj)");
			htmlAll.append("{");
			//----------------------------
			htmlAll.append("var index = obj.selectedIndex;");
			htmlAll.append("var panduan = obj.id;");
			htmlAll.append("var opnvalue = obj.options[index].value;");
			htmlAll.append("if(panduan==^XZ^){");
			htmlAll.append("var fu=obj.getAttribute('fu');");
			
			htmlAll.append("if(fu~=null&&fu~='')");
			htmlAll.append("{");
			htmlAll.append("var zisele=fu;");
			htmlAll.append("var js=zisele.split(',');");
			htmlAll.append("for(var i=0;i<js.length;i++){");
			htmlAll.append("zisele=js[i];");
			htmlAll.append("var sele=document.getElementById(zisele);");
			htmlAll.append("if(f==1)");
			htmlAll.append("{");
			htmlAll.append("ops=sele.innerHTML;");
			htmlAll.append("sessionStorage.setItem('htl',ops);");
			htmlAll.append("f=2;");
			htmlAll.append("}");
			//新添加
			htmlAll.append("var sel = obj.parentNode.parentNode.childNodes;");
			htmlAll.append("var $sel = $(sel);");
			htmlAll.append("var $sels=$sel.children('select');");
			htmlAll.append("for (var i = 0; i < $sels.length; i++) {");
			htmlAll.append("if($sels.eq(i).attr('id')==zisele)");
			htmlAll.append("{");
			htmlAll.append("sele=$sels.eq(i);");
			htmlAll.append("}");
			htmlAll.append("}");
		        
			htmlAll.append("var $jqsel = $(sele);");
			htmlAll.append("$jqsel.empty();");
			htmlAll.append(" var str=sessionStorage.getItem('htl');");
			htmlAll.append("var zz=/![<\\w\\s>=\\\"]+[\\u4e00-\\u9fa5a-zA-Z0-9\\s]*[<\\W\\S>/]{9}/;");
			htmlAll.append("var lsstr='';");
			htmlAll.append("lsstr=zz.exec(str);");
			htmlAll.append("ops=str.split(zz);");
		    htmlAll.append(" while(true)");
		    htmlAll.append("{");
			htmlAll.append("var zzs=/[0-9]+/;");
			htmlAll.append("var sz =zzs.exec(lsstr);");
			htmlAll.append("sz+='';");
			htmlAll.append("if(sz.indexOf(opnvalue+'')>=0)");
		    htmlAll.append("{");
			htmlAll.append("$jqsel.append(lsstr);");
		    htmlAll.append("}");
			htmlAll.append("str=ops[1];");
			htmlAll.append(" ops=str.split(zz);");
			htmlAll.append("lsstr=zz.exec(str);");
			htmlAll.append(" if(str.length<10)");
		    htmlAll.append(" {");
			htmlAll.append("break;");
			htmlAll.append("}");
	        htmlAll.append("}");
            htmlAll.append("}");
			htmlAll.append("}");
			htmlAll.append("else ");
			htmlAll.append("{");
			htmlAll.append(" if('zi' in obj)");
			htmlAll.append("{");
//			  //子级联的逻辑
			htmlAll.append("}");
			htmlAll.append("}");
			htmlAll.append("}");
			htmlAll.append("else");
			htmlAll.append("{");
		    //需要查的级联关系
            htmlAll.append("var fu=obj.getAttribute('fu');");
            htmlAll.append("var zbid=document.getElementById('zbid').value;");
			htmlAll.append("if(fu~=null&&fu~='')");
			htmlAll.append("{");
		    htmlAll.append("$.ajax( {");
		    htmlAll.append("type : 'post',");
		    htmlAll.append("url : '/insect/cesdm.do?ACT_TYPE=QUERY',");
		    htmlAll.append("data : {");
		    htmlAll.append("code : opnvalue,");
		    htmlAll.append("'zbid':zbid");
		    htmlAll.append("},");
		    htmlAll.append("dataType : 'json',");
		    htmlAll.append("async : true,");
		    htmlAll.append("error : function(XMLResponse) {},");
		    htmlAll.append("success : function(data) {");
		    htmlAll.append("var zisele=fu;");
		    htmlAll.append("var js=zisele.split(',');");
		    htmlAll.append("for(var i=0;i<js.length;i++){");
		    htmlAll.append("zisele=js[i];");
			htmlAll.append("var futr = obj.parentNode.parentNode.childNodes;");
			htmlAll.append("var $futr = $(futr);");
			htmlAll.append("var $ziseles=$futr.children('select');");
			htmlAll.append("for (var j = 0; j < $ziseles.size(); j++) {");
			htmlAll.append("if($ziseles.eq(j).attr('id')==zisele){");
			htmlAll.append("sele=$ziseles.eq(j);");
			htmlAll.append("}");
			htmlAll.append("}");
		    htmlAll.append("var $jqsel = $(sele);");
		    htmlAll.append("$jqsel.empty();");
		    htmlAll.append("$.each(data, function(key, val) {");
		    //遍历多map
		    htmlAll.append("if($jqsel.attr('id')==key)");
		    htmlAll.append("{");
		    htmlAll.append("$.each(val, function(key, val) {");
		    htmlAll.append("$jqsel.append('<option value='+key+'>'+val+'</option>');");
		    htmlAll.append("});");
		    htmlAll.append("}");
		    htmlAll.append("});");
		    htmlAll.append("}");
		    htmlAll.append("}");
		    htmlAll.append("});");
		    htmlAll.append("}");
	        htmlAll.append("}");
			//----------------------------
			htmlAll.append("}");
			htmlAll.append("var jsgs = new Array();");
			htmlAll.append("var gsjg = new Array();");
			htmlAll.append("$(document).keyup(function(event){");
			htmlAll.append("f_jsgs(event.target);");
			htmlAll.append("});");
			htmlAll.append("var jygx = new Array();");
			htmlAll.append("var jyts = new Array();");
			htmlAll.append("$(document).ready(function(){");
			htmlAll.append("$('#btnAddRow').click(function(){"); 
			htmlAll.append("add_row();");
			htmlAll.append("});");
			htmlAll.append("$('#btnDel').click(function(){");
			htmlAll.append("del_row();");
			htmlAll.append("});");
			htmlAll.append("$('#btnSave').click(function(){");
			htmlAll.append("$('#bbzt').val('bc');");
			htmlAll.append("f_jygx();");
			htmlAll.append("var delid = document.getElementsByName('delid')[0].value;");
			htmlAll.append("var zbid=document.getElementById('zbid').value;");
			htmlAll.append("var rwid=document.getElementsByName('rwid')[0].value;");
			htmlAll.append("var lb=document.getElementsByName('tblb')[0].value;");
			htmlAll.append("var rw = document.getElementsByName('rw')[0].value;");
			htmlAll.append("document.forms[0].action = '/insect/sjtb/add_ht.jsp?jfid='+delid+'&zbid='+zbid+'&rwid='+rwid+'&lb='+lb+'&rw='+rw;");
			//新添加的
			htmlAll.append("var tj=true;");
			htmlAll.append("var ips=document.getElementsByTagName(^input^);");
			htmlAll.append("for ( var i = 0; i < ips.length; i++) {");
			htmlAll.append("var nulable=ips[i].getAttribute('nullable');");
			htmlAll.append("if(nulable~=null)");
			htmlAll.append("{");
			htmlAll.append("if(verifyInput(ips[i]))");
			htmlAll.append("{");
			htmlAll.append("tj=true;");
			htmlAll.append("}");
			htmlAll.append("else");
			htmlAll.append("{");
			htmlAll.append("tj=false;");
			htmlAll.append("break;");
			htmlAll.append("}");
		    htmlAll.append("}");
	        htmlAll.append("}");
	        //select校验
	        htmlAll.append("if(tj)");
	        htmlAll.append("{");
	        htmlAll.append("var selects=document.getElementsByTagName(^select^);");
	        htmlAll.append("for ( var j = 0; j < selects.length; j++) {");
	        htmlAll.append("var nulable=selects[j].getAttribute('nullable');");
	        htmlAll.append("if(nulable~=null){");
	        htmlAll.append("if(verifyInput(selects[j])){");
	        htmlAll.append("tj=true;");
	        htmlAll.append("}else{");
	        htmlAll.append("tj=false;");
	        htmlAll.append("break;");
	        htmlAll.append("}");
	        htmlAll.append("}");
	        htmlAll.append("}");
	        htmlAll.append("}");
			
	        
	        htmlAll.append("if(tj)");
	        htmlAll.append("{");
	        htmlAll.append("document.forms[0].submit();");
	        htmlAll.append("}");
	        htmlAll.append("else");
	        htmlAll.append("{");
	        htmlAll.append("return;");
	        htmlAll.append("}");
	        
			
			htmlAll.append("});");
			htmlAll.append("$('#btnSubmit').click(function(){");
		    htmlAll.append("$('#bbzt').val('tj');");
			htmlAll.append("$('input[name*=^_HEAD:ZT^]').val('1');");
			htmlAll.append("f_jygx();");
		    htmlAll.append("document.forms[0].submit();");
			htmlAll.append("});");
			htmlAll.append("$('#okUp').click(function(){"); // upload
			htmlAll.append("var path = $('#file').val();");
			htmlAll.append("var delid = document.getElementsByName('delid')[0].value;");
			htmlAll.append("if (path.indexOf('.xls') > 0) {");
			htmlAll.append("var _con_ = '';");
			htmlAll.append("$('input[name*=^_HEAD^]').each(function(){");
			htmlAll.append("_con_ += $(this).attr('name') + ',' + $(this).val() + '@';");
			htmlAll.append("});");
			htmlAll.append("$('#f2').attr('action', $('#f2').attr('action') + '&hd=' + _con_+'&lujing='+path+'&deltid='+delid);");
			htmlAll.append("$('#f2').submit();");
			htmlAll.append("} else {");
			htmlAll.append("alert('请选择Excel格式文件');");
			htmlAll.append("}");
			htmlAll.append("});");
			htmlAll.append("$('#btnUpload').click(function(){");
			htmlAll.append("$('#upLayer').show();");
			htmlAll.append("});");
			htmlAll.append("$('#cancelUp').click(function(){"); 
			htmlAll.append("$('#upLayer').hide();");
			htmlAll.append("});");
			htmlAll.append("if (document.getElementById('hbs')) {");
			htmlAll.append("$('#f2').attr('action', $('#f2').attr('action') + '&hbs=1');");
			htmlAll.append("}");
			htmlAll.append("});");
			htmlAll.append("function scexcel(zbid,jfid)");
			htmlAll.append("{");
			htmlAll.append("$.ajax({");
			htmlAll.append("type:'post',");
			htmlAll.append("url:'/insect/scExcel.do?ACT_TYPE=QUERY',");
			htmlAll.append("data:{code:zbid,jfid:jfid},");
			htmlAll.append("dataType:'json',");        
			htmlAll.append("async: false,");
			htmlAll.append("error:function(XMLResponse){");
			htmlAll.append("alert('失败');");
			htmlAll.append("},");
			htmlAll.append("success:function(data){");
			htmlAll.append("document.getElementById('mb').href='system\\\\excelload\\\\D'+zbid+'.xls';");
			htmlAll.append("document.getElementById('mb').click();");
			htmlAll.append("}");
			htmlAll.append("});");
			htmlAll.append("}");
			htmlAll.append("</script>");
			htmlAll.append("</head>");
			htmlAll.append("<body>");
			htmlAll.append("<form id='f1' name='f1' action='/insect/sjtb/add_ht.jsp' method='post'>");
			htmlAll.append("<%");
			htmlAll.append("String zbid =(String)request.getAttribute('zbid');");
			htmlAll.append("String rwid =(String)request.getAttribute('rwid');");
			htmlAll.append("String lb =(String)request.getAttribute('lb');");
			htmlAll.append("String jfid = (String) request.getAttribute('jfid');");
			htmlAll.append("String rw = (String) request.getAttribute('rw');");
			htmlAll.append("String bbzt=request.getParameter('bbzt');");
			htmlAll.append("String shbz = request.getParameter('shbz');");
			htmlAll.append("if(bbzt==null)");
			htmlAll.append("{");
			htmlAll.append("bbzt='0';");
			htmlAll.append("}");
			htmlAll.append("String cxbm=(String)request.getAttribute('cxbm');");
			htmlAll.append("String cxbmmc=(String)request.getAttribute('cxbmmc');");
			htmlAll.append("String cxzt=(String)request.getAttribute('cxzt');");
			htmlAll.append("String cxuserid = (String) request.getAttribute('cxuserid');");
			htmlAll.append("String cxxz = (String) request.getAttribute('cxxz');");
			htmlAll.append("String cxcun = (String) request.getAttribute('cxcun');");
			htmlAll.append("String rwsj = (String) request.getAttribute('rwsj');");
			htmlAll.append("String zt='';");
			htmlAll.append("if(cxzt.equals('1'))");
			htmlAll.append("{");
			htmlAll.append("zt='提交';");
			htmlAll.append("}");
			htmlAll.append("else");
			htmlAll.append("{");
			htmlAll.append("zt='初始';");
			htmlAll.append("}");
			htmlAll.append("String cxlrrq=(String)request.getAttribute('cxlrrq');");
			htmlAll.append("String cxlrry=(String)request.getAttribute('cxlrry');");
			htmlAll.append("request.setAttribute('BBZT', 'bc');");
			htmlAll.append("String usebm=((User)request.getSession().getAttribute('user')).getBmbm();");
			htmlAll.append("String jfdeptprop = ((User) request.getSession().getAttribute('user')).getJfdeptprop();");
			htmlAll.append("if(cxbm~=null&&~cxbm.equals(''))");
			htmlAll.append("{");
			htmlAll.append("usebm = cxbm;");
			htmlAll.append("}");	
			//3.15新改动
			htmlAll.append("String userbmbm=usebm;");
			htmlAll.append("if(usebm.equals('10'))");
			htmlAll.append("{");
			htmlAll.append("cxbm='JFDSYS05_CODE=^'+cxbm+'^';");
			htmlAll.append("request.setAttribute('usebm', cxbm);");
			htmlAll.append("request.setAttribute('usecun', cxbm);");
			htmlAll.append("}");
			htmlAll.append(" else");
			htmlAll.append(" {");
			htmlAll.append("if(usebm.trim().length()==4)");
			htmlAll.append("{");
			htmlAll.append("String xz = ((User) request.getSession().getAttribute('user')).getXz();");
			htmlAll.append("String cun = ((User) request.getSession().getAttribute('user')).getCun();");
			htmlAll.append("if(cxxz~=null&&~cxxz.equals(''))");
			htmlAll.append("{");
			htmlAll.append("xz=cxxz;");
			htmlAll.append("cun=cxcun;");
			htmlAll.append("}");
			htmlAll.append("usebm='JFREGCODE=^'+xz+'^';");
			htmlAll.append("String usecun='JFREGCODE=^'+cun+'^';");
			htmlAll.append("request.setAttribute('usebm', usebm);");
			htmlAll.append("request.setAttribute('usecun', usecun);");
			htmlAll.append("}");
			htmlAll.append("else");
			htmlAll.append("{");
			htmlAll.append("usebm='JFDSYS05_CODE=^'+usebm+'^';");
			htmlAll.append("request.setAttribute('usebm', usebm);");
			htmlAll.append("request.setAttribute('usecun', usebm);");
			htmlAll.append("}");
			htmlAll.append(" }");
			//新添加时间
			htmlAll.append("String bmmc = ((User) request.getSession().getAttribute('user')).getBmmc();");
			htmlAll.append("if(usebm.equals('10'))");
			htmlAll.append("{");
			htmlAll.append("bmmc=cxbmmc;");
			htmlAll.append("}");
			htmlAll.append("if(cxbmmc~=null&&~cxbmmc.equals(''))");
			htmlAll.append("{");
			htmlAll.append("bmmc = cxbmmc;");
			htmlAll.append("}");
			htmlAll.append("String username = ((User) request.getSession().getAttribute('user')).getUsername();");
			htmlAll.append("if(usebm.equals('10'))");
			htmlAll.append("{");
			htmlAll.append("username=cxlrry;");
			htmlAll.append("}");
			htmlAll.append("if(cxlrry~=null&&~cxlrry.equals(''))");
			htmlAll.append("{");
			htmlAll.append("username = cxlrry;");
			htmlAll.append("}");
			htmlAll.append("String userid = ((User) request.getSession().getAttribute('user')).getUserjfid();");
			htmlAll.append("if(cxuserid~=null&&~cxuserid.equals(''))");
			htmlAll.append("{");
			htmlAll.append("userid=cxuserid;");
			htmlAll.append("}");
			htmlAll.append("Date date=new Date();");
			htmlAll.append("DateFormat format=new SimpleDateFormat('yyyy-MM-dd HH:mm:ss');");
			htmlAll.append("String time=format.format(date);");
			htmlAll.append("if(usebm.equals('10'))");
			htmlAll.append("{");
			htmlAll.append("time=cxlrrq;");
			htmlAll.append("}");
			htmlAll.append("if(cxlrrq~=null&&~cxlrrq.equals(''))");
			htmlAll.append("{");
			htmlAll.append("time = cxlrrq;");
			htmlAll.append("}");
			htmlAll.append("%>");
			//调用drawtable
			DrawTable dt = new DrawTable();
			String html = dt.draw_table(jfid, "0", so.httpServletRequest);
			htmlAll.append(html);
			htmlAll.append("<input type='hidden' name='zbid' id='zbid' value='<%=zbid %>' />");
			htmlAll.append("<input type='hidden' name='rwid' value='<%=rwid %>' />");
			htmlAll.append("<input type='hidden' name='tblb' value='<%=lb %>' />");
			htmlAll.append("<input type='hidden' name='jfid' value='<%=jfid%>' />");
			htmlAll.append("<input type='hidden' name='rw' value='<%=rw%>' />");
			htmlAll.append("<input type='hidden' name='bbzt' id='bbzt' value='bc' />");
			htmlAll.append("</form>");
			htmlAll.append("<div id='upLayer' style='display:none; width:300px; font-size:12px; border:#D8D8D8 4px solid; position:absolute; left:600px; top:100px; background-color:#F6F6F6'>");
			htmlAll.append("<form id='f2' name='f2' action='/insect/sjtb/xls_upload.jsp?zbid=<%=zbid %>&rwid=<%=rwid %>&lb=<%=lb %>&rwsj=<%=rw %>&bbzt=<%=bbzt %>' method='post' enctype='multipart/form-data'>");
			htmlAll.append("<table style='text-align: center;width:100%'>");
			htmlAll.append("<tr>");
			htmlAll.append("<td><align center>请录入需要上载的文件</align></td>");
			htmlAll.append("</tr>");
			htmlAll.append("<tr>");
			htmlAll.append("<td>");
			htmlAll.append("<input id='file' name='file' type='file' style='width:90%'>");
			htmlAll.append("</td>");
			htmlAll.append("</tr>");
			htmlAll.append("<tr>");
			htmlAll.append("<td>");
			htmlAll.append("<input type='button' value='确认' id='okUp'>&nbsp;&nbsp;");
			htmlAll.append("<input type='button' value='取消' id='cancelUp'>");
			htmlAll.append("</td>");
			htmlAll.append("</tr>");
			htmlAll.append("</table>");
			htmlAll.append("</form>");
			htmlAll.append("</div>");
			htmlAll.append("</body>");
			htmlAll.append("</html>");
			String htmlNew=htmlAll.toString().replace("'", "\"");
			htmlNew=htmlNew.replace("^","\'");
			htmlNew=htmlNew.replace("!","^");
			htmlNew=htmlNew.replace("~","!");
			//----------------------------------------------------------------
			//生成jsp文件
			String path =so.httpServletRequest.getSession().getServletContext().getRealPath("")+"\\system\\bbtj";
			File f = new File(path);
			if (!f.exists()) {
				f.mkdirs();
			}
			String fileName = "D"+jfid+".jsp";
			File file = new File(f, fileName);
			FileWriter writer = new FileWriter(file, true);
			writer.write(htmlNew.toString());
			writer.close();
			if (!file.exists()) {
				try {
					file.createNewFile();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}

			JSONObject jsonObj=JSONObject.fromObject("{'msg':'生成成功'}");
			so.httpServletResponse.getWriter().print(jsonObj);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
